# Generated by Django 4.1.2 on 2023-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
