# Generated by Django 4.1.2 on 2023-02-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reja',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
