# Generated by Django 4.1.2 on 2023-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reja', '0002_reja_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reja',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
